source 'https://rubygems.org'


gem 'atlassian-jwt'
gem 'capybara'
gem 'chromedriver-helper'
gem 'cucumber'
gem 'jira-ruby'
gem 'pry'
gem 'rake'
gem 'require_all'
gem 'rest-client'
gem 'rspec'
gem 'selenium-webdriver'
gem 'telegram-bot-ruby'
