source 'https://rubygems.org'

gem 'capybara'
gem 'chromedriver-helper'
gem 'cucumber'
gem 'parallel_tests'
gem 'pry'
gem 'rake'
gem 'require_all'
gem 'rest-client'
gem 'rspec'
gem 'selenium-webdriver'
